swagger: '2.0'
info:
  description: 'for tap'
  version: '0.0.4'
  title: 'Okaimono'
consumes:
  - application/json
produces:
  - application/json
paths:
  /card:
    post:
      summary: '会員証を新規に発行するAPI'
      responses:
        '201':
          description: '成功時'
          headers:
            location:
              description: '発行された会員証のURL: /card/${memberId}'
              type: string
          schema:
            $ref: '#/definitions/Member'
        default:
          description: '失敗時'
          schema:
            $ref: '#/definitions/Error'
      parameters:
        - in: body
          name: RegisterMemberRequest
          schema: 
            type: object
            required:
              - companyId
            properties: 
              companyId:
                type: string
      operationId: CreateMembershipCard
  /card/{memberId}:
    get:
      summary: '会員証をバーコードで取得するAPI'
      responses:
        '200':
          description: '成功時'
          schema:
            $ref: '#/definitions/Barcode'
        default:
          description: '失敗時'
          schema:
            $ref: '#/definitions/Error'
      parameters:
        - name: memberId
          in: path
          required: true
          type: string
      operationId: GetMembershipCard
definitions:
  Error:
    type: object
    properties: 
      code:
        type: integer
        format: int32
      message:
        type: string
  Member:
    type: object
    properties: 
      memberId:
        type: string
  Barcode:
    type: object
    required:
      - barcode
      - token
    properties: 
      barcode:
        type: string
      token:
        type: string

